#!/usr/bin/env bash
# $Id: drush,v 1.3 2009/05/14 07:02:18 grugnog Exp $
#
# This script is a simple wrapper that will run Drush with the most appropriate
# php executable it can find.
#

# Export the columns environment variable, so it is easily accessible to drush.
export COLUMNS

# Special case for MAMP, since it is not the default php on a vanilla install.
if [ -f /Applications/MAMP/bin/php5/bin/php ]; then
  /Applications/MAMP/bin/php5/bin/php drush.php
else
  # We check for a command line (cli) version of php, and if found use that.
  /usr/bin/env php-cli -v &> /dev/null
  if [ "$?" = 0 ] ; then
    /usr/bin/env php-cli drush.php
  else
    # Alternatively we run with straight php, which works on most other systems.
    /usr/bin/env php drush.php
  fi
fi
