Document: drush
Title: Debian drush Manual
Author: <insert document author here>
Abstract: This manual describes what drush is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/drush/drush.sgml.gz

Format: postscript
Files: /usr/share/doc/drush/drush.ps.gz

Format: text
Files: /usr/share/doc/drush/drush.text.gz

Format: HTML
Index: /usr/share/doc/drush/html/index.html
Files: /usr/share/doc/drush/html/*.html


